---
title: "Life Expectancy Analysis"
author: "Zaw Htet Wai"
date: "Saturday, Apr 25, 2015"
output:
  ioslides_presentation:
    transition: faster
runtime: shiny
mathjax: local
---

## Background
 - To give insight on life expectancy of all countries over the world from year 1990 to 2012.
 - Data are obtained from from the <b>Global Health Observatory (GHO)</b>.
 - Source: http://apps.who.int/gho/data/node.main.3?lang=en

## Preparation
- Data are cleansed and formatted as 2 sets.
- One for at birth and another for at age 60.

```{r, echo=FALSE, warning=FALSE}
source("data_process.R")
birth_exp <- load_birth_exp()
sixty_exp <- load_sixty_exp()
head(birth_exp, 5)
head(sixty_exp, 5)
```

## Breakfast
```{r setup, message = F, echo = F}
require(rCharts)
options(RCHART_WIDTH = 800, RCHART_HEIGHT = 500)
knitr::opts_chunk$set(comment = NA, results = 'asis', tidy = F, message = F)
```


## NVD3 Scatterplot

```{r nvd3plot, results = 'asis', comment = NA, message = F, echo = F}
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1$show('inline')
```

---

## NVD3 Plot Iframe

```{r nvd3plot2, results = 'asis', comment = NA, message = F, echo = F} 
require(rCharts)
n1 <- nPlot(mpg ~ wt, data = mtcars, type = 'scatterChart')
n1
```
## In the evening
